import uuid
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(help_text='Natural language input query')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parsed_intent', models.JSONField(blank=True, default=dict, help_text='Parsed category, location, radius, filters')),
                ('leads_found_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('business_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_person', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.TextField(blank=True, default='')),
                ('locality', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(db_index=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(default='India', max_length=64)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('website_status', models.CharField(choices=[('verified_present', 'Verified Present'), ('likely_present', 'Likely Present'), ('likely_absent', 'Likely Absent'), ('unknown', 'Unknown'), ('inaccessible', 'Inaccessible / Broken')], db_index=True, default='unknown', max_length=32)),
                ('website_url', models.URLField(blank=True, default='', max_length=500)),
                ('website_confidence', models.FloatField(default=0.5, help_text='0.0 to 1.0 confidence score')),
                ('google_profile_present', models.BooleanField(default=False)),
                ('social_profiles', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('review_summary', models.TextField(blank=True, default='')),
                ('services', models.JSONField(blank=True, default=list)),
                ('hours', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('field_confidence', models.JSONField(blank=True, default=dict)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('lead_score', models.IntegerField(default=50, help_text='Configurable 0-100 score')),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('calling_approved', models.BooleanField(default=False, help_text='Explicit user approval gate')),
                ('opted_out', models.BooleanField(default=False, help_text='Lead requested not to be contacted (DNC)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.searchjob')),
            ],
            options={
                'ordering': ['-lead_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoverySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=128)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.8)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=64)),
                ('source_a', models.CharField(max_length=128)),
                ('value_a', models.TextField()),
                ('source_b', models.CharField(max_length=128)),
                ('value_b', models.TextField()),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calling', 'Calling'), ('connected', 'Connected'), ('completed', 'Completed'), ('failed', 'Failed'), ('opted_out', 'Opted Out / Refused'), ('escalated', 'Escalated to Human')], default='pending', max_length=32)),
                ('telephony_provider', models.CharField(default='mock_telephony', max_length=64)),
                ('consent_given', models.BooleanField(default=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('audio_url', models.CharField(blank=True, default='', max_length=500)),
                ('call_script_version', models.CharField(default='v1.0-qualification', max_length=64)),
                ('error_reason', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallTranscriptTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(choices=[('agent', 'AI Voice Agent'), ('lead', 'Lead / Business Owner'), ('system', 'System / Event')], max_length=16)),
                ('text', models.TextField()),
                ('turn_index', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentiment', models.CharField(blank=True, default='neutral', max_length=32)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_turns', to='leads.callsession')),
            ],
            options={
                'ordering': ['turn_index'],
            },
        ),
        migrations.CreateModel(
            name='ConversationIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='Executive summary of call')),
                ('pain_points', models.JSONField(blank=True, default=list, help_text='List of business pain points')),
                ('goals', models.JSONField(blank=True, default=list, help_text='Business goals stated')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='Explicit requirements')),
                ('current_process_and_tools', models.TextField(blank=True, default='')),
                ('stated_website_presence', models.TextField(blank=True, default='')),
                ('desired_solution', models.TextField(blank=True, default='')),
                ('budget_signal', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low / Tight'), ('medium', 'Medium / Standard'), ('high', 'High / Enterprise'), ('explicit_amount', 'Explicit Amount Stated')], default='unknown', max_length=32)),
                ('budget_amount', models.CharField(blank=True, default='', max_length=64)),
                ('timeline', models.CharField(blank=True, default='Immediate', max_length=128)),
                ('decision_maker_status', models.CharField(blank=True, default='Confirmed Owner/Decision Maker', max_length=128)),
                ('objections', models.JSONField(blank=True, default=list)),
                ('buying_intent', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('customer_quotes', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.callsession')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_statement', models.TextField(help_text='What the business actually needs based on evidence')),
                ('evidence_online', models.TextField(blank=True, default='', help_text='Online research evidence')),
                ('evidence_call', models.TextField(blank=True, default='', help_text='Call transcript evidence')),
                ('opportunity', models.TextField(help_text='Where we can drive massive ROI')),
                ('recommended_solutions', models.JSONField(default=list, help_text='Prioritized features/services')),
                ('fit_rationale', models.TextField(help_text='Why this solution specifically fits this business')),
                ('offer_packages', models.JSONField(default=list, help_text='Suggested tier packages (Starter, Pro, Elite)')),
                ('pricing_guidance', models.TextField(blank=True, default='')),
                ('pitch_script', models.TextField(help_text='Personalized pitch and hook')),
                ('objections_and_responses', models.JSONField(default=list, help_text='Matrix of likely objections and rebuttals')),
                ('lead_score', models.IntegerField(default=50)),
                ('score_reasoning', models.TextField(blank=True, default='')),
                ('next_action', models.TextField(help_text='Immediate recommended next step')),
                ('follow_up_date', models.CharField(blank=True, default='Within 24-48 hours', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='leads.lead')),
                ('search_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='leads.searchjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
