# Generated by Django 5.2.17 on 2026-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='call_type',
            field=models.CharField(default='web_voice', help_text='web_voice, twilio_phone, simulation', max_length=32),
        ),
        migrations.AddField(
            model_name='callsession',
            name='collected_queries',
            field=models.JSONField(blank=True, default=list, help_text='List of queries collected during call'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='custom_business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='callsession',
            name='target_phone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='conversationintelligence',
            name='action_items',
            field=models.JSONField(blank=True, default=list, help_text='Specific follow up action items agreed upon'),
        ),
        migrations.AddField(
            model_name='conversationintelligence',
            name='collected_queries',
            field=models.JSONField(blank=True, default=list, help_text='Explicit questions and queries asked by the lead during call'),
        ),
        migrations.AddField(
            model_name='conversationintelligence',
            name='interest_status',
            field=models.CharField(choices=[('interested_hot', 'Interested (Ready for Sales Pitch)'), ('interested_warm', 'Warm Lead (Exploring)'), ('call_back', 'Call Back Requested'), ('not_interested', 'Not Interested'), ('opted_out', 'Opted Out / Do Not Call')], default='interested_warm', max_length=32),
        ),
        migrations.AddField(
            model_name='conversationintelligence',
            name='next_sales_pitch_hook',
            field=models.TextField(blank=True, default='', help_text='Tailored closing sales pitch addressing their collected queries'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
